steps:

# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=./devops/steps/001_ConfigMap.yaml
#   - --location=$_LOCATION
#   - --cluster=$_CLUSTER

- name: gcr.io/cloud-builders/kubectl
  envs:
  - 'CLOUDSDK_COMPUTE_ZONE=$_LOCATION'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
  args:
  - create
  - secret
  - generic
  - holotools-keys
  - --from-literal=google_api_key=$_GOOGLE_API_KEY
  - --from-literal=google_service_json=$_GOOGLE_SERVICE_JSON

# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=./devops/steps/003_cache-service.yaml
#   - --location=$_LOCATION
#   - --cluster=$_CLUSTER

# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=./devops/steps/004_client-api-service.yaml
#   - --location=$_LOCATION
#   - --cluster=$_CLUSTER

# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=./devops/steps/005_client-api-ingress.yaml
#   - --location=$_LOCATION
#   - --cluster=$_CLUSTER

# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=./devops/steps/006_client-web-service.yaml
#   - --location=$_LOCATION
#   - --cluster=$_CLUSTER

# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=./devops/steps/007_client-web-ingress.yaml
#   - --location=$_LOCATION
#   - --cluster=$_CLUSTER

substitutions:
  _LOCATION:
  _CLUSTER:
  _GOOGLE_API_KEY:
  _GOOGLE_SERVICE_JSON: