steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./devops/steps/001_ConfigMap.yaml
  - --filename=./devops/steps/001b_ConfigMap2.yaml
  - --location=asia-northeast1-a	
  - --cluster=holotools

# - name: gcr.io/cloud-builders/kubectl
#   args:
#   - create
#   - secret
#   - generic
#   - holotools
#   - --from-literal=google_api_key=$_GOOGLE_API_KEY
#   - --from-literal=google_service_json=$_GOOGLE_SERVICE_JSON

# substitutions:
#   _GOOGLE_API_KEY:
#   _GOOGLE_SERVICE_JSON: