steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/holotools/client-web", "./services/client-web"]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/holotools/client-web"]
- name: "ubuntu"
  args: ["sed", "-i", "s/PROJECT_ID/$PROJECT_ID/", './services/client-web/deploy.yaml']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./services/client-web/deploy.yaml
  - --image=gcr.io/$PROJECT_ID/holotools/client-web
  - --location=asia-northeast1-a	
  - --cluster=holotools