---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "client-web"
  namespace: "default"
  labels:
    app: "client-web"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "client-web"
  template:
    metadata:
      labels:
        app: "client-web"
    spec:
      containers:
      - name: "client-web-1"
        image: "gcr.io/PROJECT_ID/holotools/client-web"
        env:
        - name: "NODE_ENV"
          valueFrom:
            configMapKeyRef:
              key: "NODE_ENV"
              name: "holotools-config"
        - name: "SERVER_PORT"
          valueFrom:
            configMapKeyRef:
              key: "SERVER_PORT"
              name: "holotools-config"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "client-web-hpa-prod"
  namespace: "default"
  labels:
    app: "client-web"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "client-web"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80